spring:

  datasource:
    url: jdbc:mysql://localhost:3306/lims-test?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: ZHANGtao2007
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 52428800
      max-request-size: 52428800
  # redis ??
  redis:
    # ??
    host: 127.0.0.1
    #    host: 47.121.214.30
    #    host: 8.152.161.165
    # ??????6379
    port: 6379
    # ?????
    database: 0
    # ??
    #    password: root2024.?
    #    password: Aa123456
    #    password:
    # ??????
    timeout: 10s
    lettuce:
      pool:
        # ???????????
        min-idle: 0
        # ???????????
        max-idle: 8
        # ????????????
        max-active: 8
        # #???????????????????????
        max-wait: -1ms


# ??????
server:
  # ????HTTP??????8080
  port: 8080
  servlet:
    # ???????
    context-path: /
  tomcat:
    # tomcat?URI??
    uri-encoding: UTF-8
    # ?????????????100
    accept-count: 1000
    threads:
      # tomcat?????????200
      max: 800
      # Tomcat?????????????10
      min-spare: 100
# MyBatis??
mybatis-plus:
  # ???????
  type-aliases-package: com.example.**.bean
  # ??mapper?????????mapper.xml????
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    capital-mode: true
    db-config:
      logic-delete-field: isDeleted  # ????????????
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 0 # ??????(??? 0)
